env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
settings:
  react:
    version: detect
  import/resolver: babel-module
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - prettier
rules:
  no-unused-vars: 1
  no-console: 1
  react/display-name: 1
  react/jsx-key: 1
  react/prop-types: 1
  prettier/prettier: 1
