env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
settings:
  react:
    version: detect
  import/resolver: babel-module
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
  - prettier
rules:
  no-unused-vars: 1
  no-console: 1
  react/display-name: 1
  react/jsx-key: 1
  react/prop-types: 1
  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 1
  prettier/prettier: 0
overrides:
  - {
      files: ['**/*.ts', '**/*.tsx'],
      parser: '@typescript-eslint/parser',
      extends:
        [
          'plugin:@typescript-eslint/eslint-recommended',
          'plugin:@typescript-eslint/recommended',
          'prettier/@typescript-eslint',
        ],
      plugins: ['@typescript-eslint'],
      rules:
        {
          react/prop-types: 0,
          '@typescript-eslint/interface-name-prefix':
            [1, { prefixWithI: always }],
          '@typescript-eslint/ban-ts-ignore': 1,
        },
    }
